import { Router } from 'express';
import { query, getRow, insert, stringifyJSON, parseJSON } from '../db.js';
import { authenticate, tenant } from '../middleware/auth.js';

const router = Router();
router.use(authenticate);
const dt = (v) => v == null ? null : (v instanceof Date ? v.toISOString() : String(v));
const member = (r) => ({ _id: r.id, id: r.id, memberNo: r.member_no, name: r.name, phone: r.phone, creditBalance: Number(r.credit_balance || 0), points: Number(r.points || 0), status: r.status, createdAt: dt(r.created_at) });
const movement = (r) => ({ _id: r.id, id: r.id, type: r.type, voucherNo: r.voucher_no, payTo: r.pay_to, amount: Number(r.amount || 0), reason: r.reason, method: r.method, createdBy: r.created_by, createdAt: dt(r.created_at) });
const attendance = (r) => ({ _id: r.id, id: r.id, userId: r.user_id, userName: r.user_name, action: r.action, code: r.code, note: r.note || '', time: dt(r.event_time) });
const shift = (r) => ({ _id: r.id, id: r.id, cashierId: r.cashier_id, openAmount: Number(r.open_amount || 0), expectedAmount: Number(r.expected_amount || 0), closeAmount: Number(r.close_amount || 0), difference: Number(r.difference_amount || 0), status: r.status, openedAt: dt(r.created_at), closedAt: dt(r.updated_at) });
const supplier = (r) => ({ _id: r.id, id: r.id, code: r.code, name: r.name, phone: r.phone, contact: r.contact, status: r.status, createdAt: dt(r.created_at) });

router.get('/members', async (req, res) => { const { orgId, storeId } = tenant(req); res.json((await query('SELECT * FROM members WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId])).map(member)); });
router.post('/members', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO members (org_id,store_id,member_no,name,phone,credit_balance,points) VALUES (?,?,?,?,?,?,?)', [orgId, storeId, b.memberNo || `M${Date.now()}`, b.name || '', b.phone || '', Number(b.creditBalance || 0), Number(b.points || 0)]); res.status(201).json(member(await getRow('SELECT * FROM members WHERE id=?', [id]))); });
router.put('/members/:id', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; await query('UPDATE members SET member_no=COALESCE(?,member_no),name=COALESCE(?,name),phone=COALESCE(?,phone),status=COALESCE(?,status) WHERE id=? AND org_id=? AND store_id=?', [b.memberNo, b.name, b.phone, b.status, req.params.id, orgId, storeId]); res.json(member(await getRow('SELECT * FROM members WHERE id=?', [req.params.id]))); });
router.post('/members/:id/top-up', async (req, res) => { const { orgId, storeId } = tenant(req); const amount = Number(req.body.amount || 0); const m = await getRow('SELECT * FROM members WHERE id=? AND org_id=? AND store_id=?', [req.params.id, orgId, storeId]); if (!m || amount <= 0) return res.status(400).json({ error: 'invalid member or amount' }); await query('UPDATE members SET credit_balance=credit_balance+? WHERE id=?', [amount, m.id]); const id = await insert('INSERT INTO member_topups (org_id,store_id,member_id,receipt_no,amount,created_by) VALUES (?,?,?,?,?,?)', [orgId, storeId, m.id, `TU${Date.now()}`, amount, req.user.id]); res.json({ member: member(await getRow('SELECT * FROM members WHERE id=?', [m.id])), topup: await getRow('SELECT * FROM member_topups WHERE id=?', [id]) }); });
router.post('/members/:id/points', async (req, res) => { const { orgId, storeId } = tenant(req); const delta = Number(req.body.delta || 0); await query('UPDATE members SET points=GREATEST(0,points+?) WHERE id=? AND org_id=? AND store_id=?', [delta, req.params.id, orgId, storeId]); await insert('INSERT INTO points_ledger (org_id,store_id,member_id,delta,reason,created_by) VALUES (?,?,?,?,?,?)', [orgId, storeId, req.params.id, delta, req.body.reason || 'manual', req.user.id]); res.json(member(await getRow('SELECT * FROM members WHERE id=?', [req.params.id]))); });
router.post('/members/:id/knock-off', async (req, res) => { const { orgId, storeId } = tenant(req); const amount = Number(req.body.amount || 0); const m = await getRow('SELECT * FROM members WHERE id=? AND org_id=? AND store_id=?', [req.params.id, orgId, storeId]); if (!m || amount <= 0 || amount > Number(m.credit_balance)) return res.status(400).json({ error: 'invalid amount' }); await query('UPDATE members SET credit_balance=credit_balance-? WHERE id=?', [amount, m.id]); res.json({ member: member(await getRow('SELECT * FROM members WHERE id=?', [m.id])), knockedOff: amount, receiptNo: `RV${Date.now()}` }); });

router.get('/finance/movements', async (req, res) => { const { orgId, storeId } = tenant(req); res.json((await query('SELECT * FROM cash_movements WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId])).map(movement)); });
router.post('/finance/movements', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO cash_movements (org_id,store_id,type,voucher_no,pay_to,amount,reason,method,created_by) VALUES (?,?,?,?,?,?,?,?,?)', [orgId, storeId, b.type || 'cash_in', b.voucherNo || `V${Date.now()}`, b.payTo || '', Number(b.amount || 0), b.reason || '', b.method || 'cash', req.user.id]); res.status(201).json(movement(await getRow('SELECT * FROM cash_movements WHERE id=?', [id]))); });
router.get('/finance/credit-notes', async (req, res) => { const { orgId, storeId } = tenant(req); const rows = await query('SELECT * FROM credit_notes WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId]); res.json(rows.map((r) => ({ _id: r.id, id: r.id, creditNo: r.credit_no, customerName: r.customer_name, orderNo: r.order_no, reason: r.reason, gst: !!r.gst, items: parseJSON(r.items), status: r.status, createdAt: dt(r.created_at) }))); });
router.post('/finance/credit-notes', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO credit_notes (org_id,store_id,credit_no,customer_name,order_no,reason,gst,items,created_by) VALUES (?,?,?,?,?,?,?,?,?)', [orgId, storeId, b.creditNo || `CN${Date.now()}`, b.customerName || '', b.orderNo || '', b.reason || '', b.gst ? 1 : 0, stringifyJSON(b.items || []), req.user.id]); res.status(201).json(await getRow('SELECT * FROM credit_notes WHERE id=?', [id])); });

router.get('/attendance', async (req, res) => { const { orgId, storeId } = tenant(req); res.json((await query('SELECT * FROM attendance_records WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId])).map(attendance)); });
router.post('/attendance', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO attendance_records (org_id,store_id,user_id,user_name,action,code,note) VALUES (?,?,?,?,?,?,?)', [orgId, storeId, req.user.id, req.user.name, b.action || 'sign_in', b.code || '', b.note || '']); res.status(201).json(attendance(await getRow('SELECT * FROM attendance_records WHERE id=?', [id]))); });

router.get('/shifts/current', async (req, res) => { const { orgId, storeId } = tenant(req); let s = await getRow('SELECT * FROM shifts WHERE org_id=? AND store_id=? AND status="open" ORDER BY id DESC LIMIT 1', [orgId, storeId]); if (!s) { const id = await insert('INSERT INTO shifts (org_id,store_id,cashier_id,open_amount,status) VALUES (?,?,?,?,?)', [orgId, storeId, req.user.id, 0, 'open']); s = await getRow('SELECT * FROM shifts WHERE id=?', [id]); } const paid = await query('SELECT * FROM orders WHERE org_id=? AND store_id=? AND status="paid" AND shift_id=?', [orgId, storeId, s.id]); const expected = Number(s.open_amount || 0) + paid.reduce((a, o) => a + Number(o.total || 0), 0); await query('UPDATE shifts SET expected_amount=? WHERE id=?', [expected, s.id]); s.expected_amount = expected; res.json({ shift: shift(s), paidOrders: paid, byMethod: {} }); });
router.post('/shifts/open', async (req, res) => { const { orgId, storeId } = tenant(req); const id = await insert('INSERT INTO shifts (org_id,store_id,cashier_id,open_amount,status) VALUES (?,?,?,?,?)', [orgId, storeId, req.user.id, Number(req.body.openAmount || 0), 'open']); res.status(201).json(shift(await getRow('SELECT * FROM shifts WHERE id=?', [id]))); });
router.post('/shifts/:id/close', async (req, res) => { const { orgId, storeId } = tenant(req); const s = await getRow('SELECT * FROM shifts WHERE id=? AND org_id=? AND store_id=? AND status="open"', [req.params.id, orgId, storeId]); if (!s) return res.status(404).json({ error: 'open shift not found' }); const paid = await query('SELECT total FROM orders WHERE shift_id=? AND status="paid"', [s.id]); const expected = Number(s.open_amount || 0) + paid.reduce((a, o) => a + Number(o.total || 0), 0); const counted = Number(req.body.closeAmount || 0); await query('UPDATE shifts SET expected_amount=?,close_amount=?,difference_amount=?,status="closed" WHERE id=?', [expected, counted, counted - expected, s.id]); res.json(shift(await getRow('SELECT * FROM shifts WHERE id=?', [s.id]))); });

router.get('/suppliers', async (req, res) => { const { orgId, storeId } = tenant(req); res.json((await query('SELECT * FROM suppliers WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId])).map(supplier)); });
router.post('/suppliers', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO suppliers (org_id,store_id,code,name,phone,contact) VALUES (?,?,?,?,?,?)', [orgId, storeId, b.code || `SUP-${Date.now()}`, b.name || '', b.phone || '', b.contact || '']); res.status(201).json(supplier(await getRow('SELECT * FROM suppliers WHERE id=?', [id]))); });
router.get('/purchases', async (req, res) => { const { orgId, storeId } = tenant(req); const rows = await query('SELECT * FROM purchase_orders WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId]); res.json(rows.map((r) => ({ _id: r.id, id: r.id, poNo: r.po_no, supplierId: r.supplier_id, items: parseJSON(r.items), total: Number(r.total || 0), status: r.status, createdAt: dt(r.created_at) }))); });
router.post('/purchases', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO purchase_orders (org_id,store_id,po_no,supplier_id,items,total) VALUES (?,?,?,?,?,?)', [orgId, storeId, b.poNo || `PO${Date.now()}`, b.supplierId || null, stringifyJSON(b.items || []), Number(b.total || 0)]); res.status(201).json(await getRow('SELECT * FROM purchase_orders WHERE id=?', [id])); });
router.post('/purchases/:id/receive', async (req, res) => { const { orgId, storeId } = tenant(req); const p = await getRow('SELECT * FROM purchase_orders WHERE id=? AND org_id=? AND store_id=?', [req.params.id, orgId, storeId]); if (!p) return res.status(404).json({ error: 'not found' }); const items = parseJSON(p.items); for (const item of items) await query('UPDATE inventory_items SET quantity=quantity+? WHERE id=? AND org_id=? AND store_id=?', [Number(item.qty || 0), Number(item.itemId), orgId, storeId]); await query('UPDATE purchase_orders SET status="received",received_at=NOW() WHERE id=?', [p.id]); res.json(await getRow('SELECT * FROM purchase_orders WHERE id=?', [p.id])); });

router.get('/reports/query', async (req, res) => { const { orgId, storeId } = tenant(req); const type = req.query.type || 'sales_by_date'; const paid = await query('SELECT order_no AS orderNo,created_at AS date,subtotal,discount,tax,total,status FROM orders WHERE org_id=? AND store_id=? AND status="paid" ORDER BY created_at DESC', [orgId, storeId]); let rows = paid; if (type === 'sales_by_payment') rows = await query('SELECT method,SUM(amount) AS amount FROM payments WHERE org_id=? AND store_id=? GROUP BY method', [orgId, storeId]); res.json({ type, from: req.query.from || null, to: req.query.to || null, rows, total: paid.reduce((s, o) => s + Number(o.total || 0), 0), count: paid.length }); });

// ---- 门店设置 / GST ----
router.get('/settings', async (req, res) => { const { orgId, storeId } = tenant(req); const rows = await query('SELECT setting_key,setting_value FROM app_settings WHERE org_id=? AND store_id=?', [orgId, storeId]); const o = {}; for (const r of rows) { try { o[r.setting_key] = JSON.parse(r.setting_value); } catch { o[r.setting_key] = r.setting_value; } } res.json(o); });
router.put('/settings', async (req, res) => { const { orgId, storeId } = tenant(req); for (const [k, v] of Object.entries(req.body || {})) { await query('INSERT INTO app_settings (org_id,store_id,setting_key,setting_value) VALUES (?,?,?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)', [orgId, storeId, k, JSON.stringify(v)]); } const rows = await query('SELECT setting_key,setting_value FROM app_settings WHERE org_id=? AND store_id=?', [orgId, storeId]); const o = {}; for (const r of rows) { try { o[r.setting_key] = JSON.parse(r.setting_value); } catch { o[r.setting_key] = r.setting_value; } } res.json(o); });

// ---- 发票 / Tax Invoice ----
router.get('/orders/:id/invoice', async (req, res) => { const { orgId, storeId } = tenant(req); const o = await getRow('SELECT * FROM orders WHERE id=? AND org_id=? AND store_id=?', [req.params.id, orgId, storeId]); if (!o) return res.status(404).json({ error: 'not found' }); const setRows = await query('SELECT setting_key,setting_value FROM app_settings WHERE org_id=? AND store_id=?', [orgId, storeId]); const s = {}; for (const r of setRows) { try { s[r.setting_key] = JSON.parse(r.setting_value); } catch { s[r.setting_key] = r.setting_value; } } const payments = await query('SELECT method,amount FROM payments WHERE order_id=?', [o.id]); res.json({ invoiceNo: o.invoice_no || `DRAFT-${o.order_no}`, orderNo: o.order_no, date: dt(o.created_at), status: o.status, seller: { name: s.companyName, address: s.address, phone: s.phone, gstNo: s.gstNo }, customer: { name: o.customer_name || 'Walk-in Customer', phone: o.phone || '' }, items: parseJSON(o.items), subtotal: Number(o.subtotal || 0), discount: Number(o.discount || 0), serviceCharge: Number(o.service_charge || 0), tax: Number(o.tax || 0), taxRate: s.taxRate, taxInclusive: s.taxInclusive, total: Number(o.total || 0), payments: payments.map((p) => ({ method: p.method, amount: Number(p.amount) })), refundedAmount: Number(o.refunded_amount || 0) }); });

// ---- Split Bill ----
router.get('/orders/:id/splits', async (req, res) => { const { orgId, storeId } = tenant(req); res.json(await query('SELECT * FROM orders WHERE org_id=? AND store_id=? AND split_from_order_id=?', [orgId, storeId, req.params.id])); });
router.post('/orders/:id/split', async (req, res) => { const { orgId, storeId } = tenant(req); const parent = await getRow('SELECT * FROM orders WHERE id=? AND org_id=? AND store_id=?', [req.params.id, orgId, storeId]); if (!parent) return res.status(404).json({ error: 'not found' }); if (!['open', 'kitchen', 'ready', 'served'].includes(parent.status)) return res.status(400).json({ error: 'cannot split this order' }); const b = req.body || {}; const items = parseJSON(parent.items); const groups = []; if (b.mode === 'item') { for (const idxs of b.groups || []) { const g = idxs.map((i) => items[i]).filter(Boolean).map((i) => ({ ...i, status: 'pending' })); if (g.length) groups.push(g); } } else if (b.mode === 'pax') { const pax = Math.max(2, Number(b.pax || 2)); const buckets = Array.from({ length: pax }, () => []); items.forEach((it, i) => buckets[i % pax].push({ ...it, status: 'pending' })); groups.push(...buckets.filter((g) => g.length)); } else { const parts = Math.max(2, Number(b.parts || 2)); const per = Math.round((Number(parent.total) / parts) * 100) / 100; for (let i = 0; i < parts; i++) { const amt = i === parts - 1 ? Math.round((Number(parent.total) - per * (parts - 1)) * 100) / 100 : per; groups.push([{ code: `SPLIT-${i + 1}`, name: `Split share ${i + 1}`, unitPrice: amt, qty: 1, status: 'pending' }]); } } if (!groups.length) return res.status(400).json({ error: 'nothing to split' }); const created = []; for (let gi = 0; gi < groups.length; gi++) { const g = groups[gi]; const sub = g.reduce((x, i) => x + Number(i.unitPrice) * Number(i.qty), 0); const id = await insert('INSERT INTO orders (org_id,store_id,order_no,type,table_id,customer_name,phone,items,subtotal,total,status,created_by,shift_id,split_from_order_id,split_group_no) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', [orgId, storeId, `${parent.order_no}-S${gi + 1}`, parent.type, parent.table_id, parent.customer_name, parent.phone, stringifyJSON(g), sub, sub, 'open', req.user.id, parent.shift_id, parent.id, gi + 1]); created.push(id); } await query('UPDATE orders SET status="split" WHERE id=?', [parent.id]); await insert('INSERT INTO order_splits (org_id,store_id,parent_order_id,mode,split_count,created_by) VALUES (?,?,?,?,?,?)', [orgId, storeId, parent.id, b.mode || 'equal', created.length, req.user.id]); res.status(201).json({ parentId: parent.id, children: created }); });

// ---- Refund ----
router.get('/refunds', async (req, res) => { const { orgId, storeId } = tenant(req); res.json((await query('SELECT * FROM refunds WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId])).map((r) => ({ _id: r.id, id: r.id, refundNo: r.refund_no, orderId: r.order_id, orderNo: r.order_no, amount: Number(r.amount || 0), method: r.method, reason: r.reason, items: parseJSON(r.items), restock: !!r.restock, createdAt: dt(r.created_at) }))); });
router.post('/orders/:id/refund', async (req, res) => { const { orgId, storeId } = tenant(req); const o = await getRow('SELECT * FROM orders WHERE id=? AND org_id=? AND store_id=?', [req.params.id, orgId, storeId]); if (!o) return res.status(404).json({ error: 'not found' }); if (!['paid', 'served'].includes(o.status)) return res.status(400).json({ error: 'only paid orders can be refunded' }); const b = req.body || {}; const restock = b.restock !== false; const items = parseJSON(o.items); let amount = Number(b.amount || 0); const refundItems = []; if (Array.isArray(b.items) && b.items.length) { for (const rl of b.items) { const src = items[rl.index] || items.find((i) => i.code === rl.code); if (!src) continue; const qty = Math.min(Number(rl.qty || src.qty), src.qty); amount += Math.round(qty * Number(src.unitPrice) * 100) / 100; refundItems.push({ code: src.code, name: src.name, qty, unitPrice: src.unitPrice }); if (restock) await query('UPDATE menu_variants SET stock_qty=stock_qty+? WHERE id=?', [qty, Number(src.variantId || src.itemId)]); } } else { amount = amount || Math.round((Number(o.total) - Number(o.refunded_amount || 0)) * 100) / 100; if (restock) for (const it of items) await query('UPDATE menu_variants SET stock_qty=stock_qty+? WHERE id=?', [Number(it.qty), Number(it.variantId || it.itemId)]); } if (amount <= 0) return res.status(400).json({ error: 'refund amount must be positive' }); const newRefunded = Math.round((Number(o.refunded_amount || 0) + amount) * 100) / 100; const newStatus = newRefunded >= Number(o.total) - 0.001 ? 'refunded' : o.status; await query('UPDATE orders SET refunded_amount=?,status=? WHERE id=?', [newRefunded, newStatus, o.id]); const id = await insert('INSERT INTO refunds (org_id,store_id,refund_no,order_id,order_no,amount,method,reason,items,restock,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?)', [orgId, storeId, `RF${Date.now()}`, o.id, o.order_no, amount, b.method || 'cash', b.reason || 'customer refund', stringifyJSON(refundItems), restock ? 1 : 0, req.user.id]); res.status(201).json({ orderId: o.id, refundedAmount: newRefunded, status: newStatus, refundId: id }); });

// ---- 促销 ----
router.get('/promotions', async (req, res) => { const { orgId, storeId } = tenant(req); const rows = await query('SELECT * FROM promotions WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId]); res.json(rows.map((r) => ({ _id: r.id, id: r.id, code: r.code, name: r.name, type: r.type, value: Number(r.value || 0), minSpend: Number(r.min_spend || 0), validFrom: dt(r.valid_from), validUntil: dt(r.valid_until), isActive: !!r.is_active }))); });
router.post('/promotions', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO promotions (org_id,store_id,code,name,type,value,min_spend,valid_from,valid_until,is_active) VALUES (?,?,?,?,?,?,?,?,?,?)', [orgId, storeId, b.code || `PROMO${Date.now()}`, b.name || '', b.type || 'percent', Number(b.value || 0), Number(b.minSpend || 0), b.validFrom || null, b.validUntil || null, b.isActive === false ? 0 : 1]); res.status(201).json(await getRow('SELECT * FROM promotions WHERE id=?', [id])); });
router.put('/promotions/:id', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; await query('UPDATE promotions SET code=COALESCE(?,code),name=COALESCE(?,name),type=COALESCE(?,type),value=COALESCE(?,value),min_spend=COALESCE(?,min_spend),is_active=COALESCE(?,is_active) WHERE id=? AND org_id=? AND store_id=?', [b.code, b.name, b.type, b.value, b.minSpend, b.isActive == null ? null : (b.isActive ? 1 : 0), req.params.id, orgId, storeId]); res.json(await getRow('SELECT * FROM promotions WHERE id=?', [req.params.id])); });
router.delete('/promotions/:id', async (req, res) => { const { orgId, storeId } = tenant(req); await query('DELETE FROM promotions WHERE id=? AND org_id=? AND store_id=?', [req.params.id, orgId, storeId]); res.json({ ok: true }); });
router.get('/promotions/apply', async (req, res) => { const { orgId, storeId } = tenant(req); const code = String(req.query.code || '').toUpperCase(); const amount = Number(req.query.amount || 0); const p = await getRow('SELECT * FROM promotions WHERE org_id=? AND store_id=? AND UPPER(code)=? AND is_active=1', [orgId, storeId, code]); if (!p) return res.status(404).json({ error: 'promotion not found' }); if (amount < Number(p.min_spend || 0)) return res.status(400).json({ error: `min spend ${p.min_spend}` }); const discount = p.type === 'percent' ? Math.round(amount * Number(p.value)) / 100 : Math.min(Number(p.value), amount); res.json({ promotionId: p.id, code: p.code, discount: Math.round(discount * 100) / 100 }); });

// ---- 客户库存 ----
router.get('/customer-stock', async (req, res) => { const { orgId, storeId } = tenant(req); const rows = await query('SELECT * FROM customer_stock WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId]); res.json(rows.map((r) => ({ _id: r.id, id: r.id, memberId: r.member_id, memberNo: r.member_no, itemName: r.item_name, qty: Number(r.qty || 0), unit: r.unit, note: r.note }))); });
router.post('/customer-stock', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO customer_stock (org_id,store_id,member_id,member_no,item_name,qty,unit,note) VALUES (?,?,?,?,?,?,?,?)', [orgId, storeId, b.memberId || null, b.memberNo || '', b.itemName || '', Number(b.qty || 0), b.unit || 'pcs', b.note || '']); res.status(201).json(await getRow('SELECT * FROM customer_stock WHERE id=?', [id])); });
router.post('/customer-stock/:id/adjust', async (req, res) => { const { orgId, storeId } = tenant(req); await query('UPDATE customer_stock SET qty=GREATEST(0,qty+?) WHERE id=? AND org_id=? AND store_id=?', [Number(req.body.delta || 0), req.params.id, orgId, storeId]); res.json(await getRow('SELECT * FROM customer_stock WHERE id=?', [req.params.id])); });

// ---- 定期盘点 ----
router.get('/stock-takes', async (req, res) => { const { orgId, storeId } = tenant(req); const rows = await query('SELECT * FROM stock_takes WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId]); res.json(rows.map((r) => ({ _id: r.id, id: r.id, takeNo: r.take_no, status: r.status, lines: parseJSON(r.lines), createdAt: dt(r.created_at), postedAt: dt(r.posted_at) }))); });
router.post('/stock-takes', async (req, res) => { const { orgId, storeId } = tenant(req); const variants = await query('SELECT id,code,name,stock_qty FROM menu_variants WHERE org_id=? AND store_id=?', [orgId, storeId]); const lines = variants.map((v) => ({ itemId: v.id, code: v.code, name: v.name, systemQty: Number(v.stock_qty || 0), countedQty: null, variance: 0 })); const id = await insert('INSERT INTO stock_takes (org_id,store_id,take_no,status,lines,created_by) VALUES (?,?,?,?,?,?)', [orgId, storeId, `ST${Date.now()}`, 'draft', stringifyJSON(lines), req.user.id]); res.status(201).json(await getRow('SELECT * FROM stock_takes WHERE id=?', [id])); });
router.put('/stock-takes/:id', async (req, res) => { const { orgId, storeId } = tenant(req); const st = await getRow('SELECT * FROM stock_takes WHERE id=? AND org_id=? AND store_id=?', [req.params.id, orgId, storeId]); if (!st) return res.status(404).json({ error: 'not found' }); const lines = parseJSON(st.lines); for (const upd of req.body?.lines || []) { const line = lines.find((l) => String(l.itemId) === String(upd.itemId)); if (line) { line.countedQty = Number(upd.countedQty || 0); line.variance = line.countedQty - line.systemQty; } } await query('UPDATE stock_takes SET lines=? WHERE id=?', [stringifyJSON(lines), st.id]); res.json({ ...st, lines }); });
router.post('/stock-takes/:id/post', async (req, res) => { const { orgId, storeId } = tenant(req); const st = await getRow('SELECT * FROM stock_takes WHERE id=? AND org_id=? AND store_id=?', [req.params.id, orgId, storeId]); if (!st) return res.status(404).json({ error: 'not found' }); if (st.status !== 'draft') return res.status(400).json({ error: 'already posted' }); for (const line of parseJSON(st.lines)) { if (line.countedQty == null) continue; await query('UPDATE menu_variants SET stock_qty=? WHERE id=? AND org_id=? AND store_id=?', [line.countedQty, line.itemId, orgId, storeId]); } await query('UPDATE stock_takes SET status="posted",posted_at=NOW() WHERE id=?', [st.id]); res.json({ ok: true }); });

// ---- 报表设计器 ----
router.get('/report-templates', async (req, res) => { const { orgId, storeId } = tenant(req); const rows = await query('SELECT * FROM report_templates WHERE org_id=? AND store_id=? ORDER BY id ASC', [orgId, storeId]); res.json(rows.map((r) => ({ _id: r.id, id: r.id, type: r.type, name: r.name, columns: parseJSON(r.columns), isSystem: !!r.is_system }))); });
router.post('/report-templates', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO report_templates (org_id,store_id,type,name,columns,is_system) VALUES (?,?,?,?,?,0)', [orgId, storeId, b.type || 'custom', b.name || 'Custom Report', stringifyJSON(b.columns || [])]); res.status(201).json(await getRow('SELECT * FROM report_templates WHERE id=?', [id])); });
router.delete('/report-templates/:id', async (req, res) => { const { orgId, storeId } = tenant(req); await query('DELETE FROM report_templates WHERE id=? AND org_id=? AND store_id=? AND is_system=0', [req.params.id, orgId, storeId]); res.json({ ok: true }); });

// ---- 硬件 ----
router.get('/hardware/printers', async (req, res) => { const { orgId, storeId } = tenant(req); const rows = await query('SELECT * FROM printers WHERE org_id=? AND store_id=? ORDER BY id ASC', [orgId, storeId]); res.json(rows.map((r) => ({ _id: r.id, id: r.id, name: r.name, target: r.target, connection: r.connection, width: Number(r.width || 80), isDefault: !!r.is_default, isActive: !!r.is_active }))); });
router.post('/hardware/printers', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO printers (org_id,store_id,name,target,connection,width,is_default,is_active) VALUES (?,?,?,?,?,?,?,?)', [orgId, storeId, b.name || 'Printer', b.target || 'receipt', b.connection || 'usb', Number(b.width || 80), b.isDefault ? 1 : 0, b.isActive === false ? 0 : 1]); res.status(201).json(await getRow('SELECT * FROM printers WHERE id=?', [id])); });
router.put('/hardware/printers/:id', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; await query('UPDATE printers SET name=COALESCE(?,name),target=COALESCE(?,target),connection=COALESCE(?,connection),width=COALESCE(?,width),is_default=COALESCE(?,is_default),is_active=COALESCE(?,is_active) WHERE id=? AND org_id=? AND store_id=?', [b.name, b.target, b.connection, b.width, b.isDefault == null ? null : (b.isDefault ? 1 : 0), b.isActive == null ? null : (b.isActive ? 1 : 0), req.params.id, orgId, storeId]); res.json(await getRow('SELECT * FROM printers WHERE id=?', [req.params.id])); });
router.post('/hardware/print', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const target = b.target || 'receipt'; const printer = await getRow('SELECT * FROM printers WHERE org_id=? AND store_id=? AND target=? AND is_active=1 LIMIT 1', [orgId, storeId, target]); const o = b.orderId ? await getRow('SELECT * FROM orders WHERE id=? AND org_id=? AND store_id=?', [b.orderId, orgId, storeId]) : null; const lines = []; if (target === 'kitchen' || target === 'bar') { lines.push(`== ${target.toUpperCase()} COPY ==`); if (o) { lines.push(o.order_no); for (const it of parseJSON(o.items)) lines.push(`${it.qty} x ${it.code} ${it.name}`); } } else if (o) { lines.push(o.order_no); for (const it of parseJSON(o.items)) lines.push(`${it.qty} x ${it.name}  ${(Number(it.unitPrice) * Number(it.qty)).toFixed(2)}`); lines.push(`TOTAL ${Number(o.total).toFixed(2)}`); } const payload = lines.join('\n'); const id = await insert('INSERT INTO print_jobs (org_id,store_id,target,printer_id,order_id,payload,created_by) VALUES (?,?,?,?,?,?,?)', [orgId, storeId, target, printer ? printer.id : null, o ? o.id : null, payload, req.user.id]); res.status(201).json({ jobId: id, printerId: printer ? printer.id : null, escpos: payload }); });
router.post('/hardware/drawer', async (req, res) => { const { orgId, storeId } = tenant(req); const id = await insert('INSERT INTO print_jobs (org_id,store_id,target,payload,status,created_by) VALUES (?,?,?,?,?,?)', [orgId, storeId, 'drawer', 'ESC/POS: 1B 70 00 19 FA', 'sent', req.user.id]); res.json({ ok: true, jobId: id }); });

// ---- GST 汇总 ----
router.get('/reports/gst', async (req, res) => { const { orgId, storeId } = tenant(req); const paid = await query('SELECT total,tax FROM orders WHERE org_id=? AND store_id=? AND status IN ("paid","refunded")', [orgId, storeId]); const setRows = await query('SELECT setting_key,setting_value FROM app_settings WHERE org_id=? AND store_id=?', [orgId, storeId]); const s = {}; for (const r of setRows) { try { s[r.setting_key] = JSON.parse(r.setting_value); } catch { s[r.setting_key] = r.setting_value; } } const outputTax = paid.reduce((x, o) => x + Number(o.tax || 0), 0); res.json({ from: req.query.from || null, to: req.query.to || null, taxRate: s.taxRate, taxInclusive: s.taxInclusive, taxableSales: paid.reduce((x, o) => x + Number(o.total || 0), 0), outputTax: Math.round(outputTax * 100) / 100, netTax: Math.round(outputTax * 100) / 100 }); });

export default router;
