import { Router } from 'express';
import { query, getRow, insert, stringifyJSON, parseJSON } from '../db.js';
import { authenticate, tenant } from '../middleware/auth.js';

const router = Router();
router.use(authenticate);
const dt = (v) => v == null ? null : (v instanceof Date ? v.toISOString() : String(v));
const member = (r) => ({ _id: r.id, id: r.id, memberNo: r.member_no, name: r.name, phone: r.phone, creditBalance: Number(r.credit_balance || 0), points: Number(r.points || 0), status: r.status, createdAt: dt(r.created_at) });
const movement = (r) => ({ _id: r.id, id: r.id, type: r.type, voucherNo: r.voucher_no, payTo: r.pay_to, amount: Number(r.amount || 0), reason: r.reason, method: r.method, createdBy: r.created_by, createdAt: dt(r.created_at) });
const attendance = (r) => ({ _id: r.id, id: r.id, userId: r.user_id, userName: r.user_name, action: r.action, code: r.code, note: r.note || '', time: dt(r.event_time) });
const shift = (r) => ({ _id: r.id, id: r.id, cashierId: r.cashier_id, openAmount: Number(r.open_amount || 0), expectedAmount: Number(r.expected_amount || 0), closeAmount: Number(r.close_amount || 0), difference: Number(r.difference_amount || 0), status: r.status, openedAt: dt(r.created_at), closedAt: dt(r.updated_at) });
const supplier = (r) => ({ _id: r.id, id: r.id, code: r.code, name: r.name, phone: r.phone, contact: r.contact, status: r.status, createdAt: dt(r.created_at) });

router.get('/members', async (req, res) => { const { orgId, storeId } = tenant(req); res.json((await query('SELECT * FROM members WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId])).map(member)); });
router.post('/members', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO members (org_id,store_id,member_no,name,phone,credit_balance,points) VALUES (?,?,?,?,?,?,?)', [orgId, storeId, b.memberNo || `M${Date.now()}`, b.name || '', b.phone || '', Number(b.creditBalance || 0), Number(b.points || 0)]); res.status(201).json(member(await getRow('SELECT * FROM members WHERE id=?', [id]))); });
router.put('/members/:id', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; await query('UPDATE members SET member_no=COALESCE(?,member_no),name=COALESCE(?,name),phone=COALESCE(?,phone),status=COALESCE(?,status) WHERE id=? AND org_id=? AND store_id=?', [b.memberNo, b.name, b.phone, b.status, req.params.id, orgId, storeId]); res.json(member(await getRow('SELECT * FROM members WHERE id=?', [req.params.id]))); });
router.post('/members/:id/top-up', async (req, res) => { const { orgId, storeId } = tenant(req); const amount = Number(req.body.amount || 0); const m = await getRow('SELECT * FROM members WHERE id=? AND org_id=? AND store_id=?', [req.params.id, orgId, storeId]); if (!m || amount <= 0) return res.status(400).json({ error: 'invalid member or amount' }); await query('UPDATE members SET credit_balance=credit_balance+? WHERE id=?', [amount, m.id]); const id = await insert('INSERT INTO member_topups (org_id,store_id,member_id,receipt_no,amount,created_by) VALUES (?,?,?,?,?,?)', [orgId, storeId, m.id, `TU${Date.now()}`, amount, req.user.id]); res.json({ member: member(await getRow('SELECT * FROM members WHERE id=?', [m.id])), topup: await getRow('SELECT * FROM member_topups WHERE id=?', [id]) }); });
router.post('/members/:id/points', async (req, res) => { const { orgId, storeId } = tenant(req); const delta = Number(req.body.delta || 0); await query('UPDATE members SET points=GREATEST(0,points+?) WHERE id=? AND org_id=? AND store_id=?', [delta, req.params.id, orgId, storeId]); await insert('INSERT INTO points_ledger (org_id,store_id,member_id,delta,reason,created_by) VALUES (?,?,?,?,?,?)', [orgId, storeId, req.params.id, delta, req.body.reason || 'manual', req.user.id]); res.json(member(await getRow('SELECT * FROM members WHERE id=?', [req.params.id]))); });
router.post('/members/:id/knock-off', async (req, res) => { const { orgId, storeId } = tenant(req); const amount = Number(req.body.amount || 0); const m = await getRow('SELECT * FROM members WHERE id=? AND org_id=? AND store_id=?', [req.params.id, orgId, storeId]); if (!m || amount <= 0 || amount > Number(m.credit_balance)) return res.status(400).json({ error: 'invalid amount' }); await query('UPDATE members SET credit_balance=credit_balance-? WHERE id=?', [amount, m.id]); res.json({ member: member(await getRow('SELECT * FROM members WHERE id=?', [m.id])), knockedOff: amount, receiptNo: `RV${Date.now()}` }); });

router.get('/finance/movements', async (req, res) => { const { orgId, storeId } = tenant(req); res.json((await query('SELECT * FROM cash_movements WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId])).map(movement)); });
router.post('/finance/movements', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO cash_movements (org_id,store_id,type,voucher_no,pay_to,amount,reason,method,created_by) VALUES (?,?,?,?,?,?,?,?,?)', [orgId, storeId, b.type || 'cash_in', b.voucherNo || `V${Date.now()}`, b.payTo || '', Number(b.amount || 0), b.reason || '', b.method || 'cash', req.user.id]); res.status(201).json(movement(await getRow('SELECT * FROM cash_movements WHERE id=?', [id]))); });
router.get('/finance/credit-notes', async (req, res) => { const { orgId, storeId } = tenant(req); const rows = await query('SELECT * FROM credit_notes WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId]); res.json(rows.map((r) => ({ _id: r.id, id: r.id, creditNo: r.credit_no, customerName: r.customer_name, orderNo: r.order_no, reason: r.reason, gst: !!r.gst, items: parseJSON(r.items), status: r.status, createdAt: dt(r.created_at) }))); });
router.post('/finance/credit-notes', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO credit_notes (org_id,store_id,credit_no,customer_name,order_no,reason,gst,items,created_by) VALUES (?,?,?,?,?,?,?,?,?)', [orgId, storeId, b.creditNo || `CN${Date.now()}`, b.customerName || '', b.orderNo || '', b.reason || '', b.gst ? 1 : 0, stringifyJSON(b.items || []), req.user.id]); res.status(201).json(await getRow('SELECT * FROM credit_notes WHERE id=?', [id])); });

router.get('/attendance', async (req, res) => { const { orgId, storeId } = tenant(req); res.json((await query('SELECT * FROM attendance_records WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId])).map(attendance)); });
router.post('/attendance', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO attendance_records (org_id,store_id,user_id,user_name,action,code,note) VALUES (?,?,?,?,?,?,?)', [orgId, storeId, req.user.id, req.user.name, b.action || 'sign_in', b.code || '', b.note || '']); res.status(201).json(attendance(await getRow('SELECT * FROM attendance_records WHERE id=?', [id]))); });

router.get('/shifts/current', async (req, res) => { const { orgId, storeId } = tenant(req); let s = await getRow('SELECT * FROM shifts WHERE org_id=? AND store_id=? AND status="open" ORDER BY id DESC LIMIT 1', [orgId, storeId]); if (!s) { const id = await insert('INSERT INTO shifts (org_id,store_id,cashier_id,open_amount,status) VALUES (?,?,?,?,?)', [orgId, storeId, req.user.id, 0, 'open']); s = await getRow('SELECT * FROM shifts WHERE id=?', [id]); } const paid = await query('SELECT * FROM orders WHERE org_id=? AND store_id=? AND status="paid" AND shift_id=?', [orgId, storeId, s.id]); const expected = Number(s.open_amount || 0) + paid.reduce((a, o) => a + Number(o.total || 0), 0); await query('UPDATE shifts SET expected_amount=? WHERE id=?', [expected, s.id]); s.expected_amount = expected; res.json({ shift: shift(s), paidOrders: paid, byMethod: {} }); });
router.post('/shifts/open', async (req, res) => { const { orgId, storeId } = tenant(req); const id = await insert('INSERT INTO shifts (org_id,store_id,cashier_id,open_amount,status) VALUES (?,?,?,?,?)', [orgId, storeId, req.user.id, Number(req.body.openAmount || 0), 'open']); res.status(201).json(shift(await getRow('SELECT * FROM shifts WHERE id=?', [id]))); });
router.post('/shifts/:id/close', async (req, res) => { const { orgId, storeId } = tenant(req); const s = await getRow('SELECT * FROM shifts WHERE id=? AND org_id=? AND store_id=? AND status="open"', [req.params.id, orgId, storeId]); if (!s) return res.status(404).json({ error: 'open shift not found' }); const paid = await query('SELECT total FROM orders WHERE shift_id=? AND status="paid"', [s.id]); const expected = Number(s.open_amount || 0) + paid.reduce((a, o) => a + Number(o.total || 0), 0); const counted = Number(req.body.closeAmount || 0); await query('UPDATE shifts SET expected_amount=?,close_amount=?,difference_amount=?,status="closed" WHERE id=?', [expected, counted, counted - expected, s.id]); res.json(shift(await getRow('SELECT * FROM shifts WHERE id=?', [s.id]))); });

router.get('/suppliers', async (req, res) => { const { orgId, storeId } = tenant(req); res.json((await query('SELECT * FROM suppliers WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId])).map(supplier)); });
router.post('/suppliers', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO suppliers (org_id,store_id,code,name,phone,contact) VALUES (?,?,?,?,?,?)', [orgId, storeId, b.code || `SUP-${Date.now()}`, b.name || '', b.phone || '', b.contact || '']); res.status(201).json(supplier(await getRow('SELECT * FROM suppliers WHERE id=?', [id]))); });
router.get('/purchases', async (req, res) => { const { orgId, storeId } = tenant(req); const rows = await query('SELECT * FROM purchase_orders WHERE org_id=? AND store_id=? ORDER BY id DESC', [orgId, storeId]); res.json(rows.map((r) => ({ _id: r.id, id: r.id, poNo: r.po_no, supplierId: r.supplier_id, items: parseJSON(r.items), total: Number(r.total || 0), status: r.status, createdAt: dt(r.created_at) }))); });
router.post('/purchases', async (req, res) => { const { orgId, storeId } = tenant(req); const b = req.body || {}; const id = await insert('INSERT INTO purchase_orders (org_id,store_id,po_no,supplier_id,items,total) VALUES (?,?,?,?,?,?)', [orgId, storeId, b.poNo || `PO${Date.now()}`, b.supplierId || null, stringifyJSON(b.items || []), Number(b.total || 0)]); res.status(201).json(await getRow('SELECT * FROM purchase_orders WHERE id=?', [id])); });
router.post('/purchases/:id/receive', async (req, res) => { const { orgId, storeId } = tenant(req); const p = await getRow('SELECT * FROM purchase_orders WHERE id=? AND org_id=? AND store_id=?', [req.params.id, orgId, storeId]); if (!p) return res.status(404).json({ error: 'not found' }); const items = parseJSON(p.items); for (const item of items) await query('UPDATE inventory_items SET quantity=quantity+? WHERE id=? AND org_id=? AND store_id=?', [Number(item.qty || 0), Number(item.itemId), orgId, storeId]); await query('UPDATE purchase_orders SET status="received",received_at=NOW() WHERE id=?', [p.id]); res.json(await getRow('SELECT * FROM purchase_orders WHERE id=?', [p.id])); });

router.get('/reports/query', async (req, res) => { const { orgId, storeId } = tenant(req); const type = req.query.type || 'sales_by_date'; const paid = await query('SELECT order_no AS orderNo,created_at AS date,subtotal,discount,tax,total,status FROM orders WHERE org_id=? AND store_id=? AND status="paid" ORDER BY created_at DESC', [orgId, storeId]); let rows = paid; if (type === 'sales_by_payment') rows = await query('SELECT method,SUM(amount) AS amount FROM payments WHERE org_id=? AND store_id=? GROUP BY method', [orgId, storeId]); res.json({ type, from: req.query.from || null, to: req.query.to || null, rows, total: paid.reduce((s, o) => s + Number(o.total || 0), 0), count: paid.length }); });

export default router;
